// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qurrah.Data;

#nullable disable

namespace Qurrah.Data.Migrations
{
    [DbContext(typeof(QurrahDbContext))]
    [Migration("20230626103757_AddGenderLangUniqueness")]
    partial class AddGenderLangUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5d1236b0-3d83-42ff-b9fe-7ffdc0c7fb84",
                            Name = "Parent",
                            NormalizedName = "Parent"
                        },
                        new
                        {
                            Id = "0a41331c-fa06-4869-af68-6cb6eebd4663",
                            Name = "Center",
                            NormalizedName = "Center"
                        },
                        new
                        {
                            Id = "7c75f593-da32-4e69-90f6-d31dce7d05b9",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "30660785-170d-4879-a50a-fbb0538fe184",
                            Name = "CenterApprover",
                            NormalizedName = "CenterApprover"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f9c63271-a583-4604-aafc-3ad89bfc701b",
                            RoleId = "7c75f593-da32-4e69-90f6-d31dce7d05b9"
                        },
                        new
                        {
                            UserId = "a5b268ff-af25-4ebb-9910-06e4e5a55446",
                            RoleId = "30660785-170d-4879-a50a-fbb0538fe184"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Qurrah.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FKCreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FKUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FKCreatedByUserId");

                    b.HasIndex("FKUserTypeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f9c63271-a583-4604-aafc-3ad89bfc701b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c56e77c-f4bd-4f67-941b-010c59c1d80f",
                            CreatedOn = new DateTime(2023, 6, 26, 12, 37, 56, 521, DateTimeKind.Local).AddTicks(2361),
                            Email = "Admin@Qurrah.com",
                            EmailConfirmed = false,
                            FKUserTypeId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "Admin@Qurrah.com",
                            NormalizedUserName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEHv3gMUbBn2OCwKoGU3GnpyD1E0CRj1IbZdFIPivnARNJrfbqiGHJpfQrro8gbKshg==",
                            PhoneNumber = "0543700744",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a4819d91-17e3-4efb-88b9-89b7f52bcf81",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "a5b268ff-af25-4ebb-9910-06e4e5a55446",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "341c5d00-5c69-421b-a2b2-9c69ce305383",
                            CreatedOn = new DateTime(2023, 6, 26, 12, 37, 56, 623, DateTimeKind.Local).AddTicks(6222),
                            Email = "CenterReviewer@Qurrah.com",
                            EmailConfirmed = false,
                            FKUserTypeId = 2,
                            LockoutEnabled = false,
                            NormalizedEmail = "CenterReviewer@Qurrah.com",
                            NormalizedUserName = "CenterReviewer",
                            PasswordHash = "AQAAAAIAAYagAAAAEDvdDjhuvWiHIYqeCcbehFaJud4JG4r8SnotqoFoaesYDHk5N1xWGOYTE1BusWdOZg==",
                            PhoneNumber = "0543700745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddee8e8b-693c-4365-8b7c-bcd47dcd004d",
                            TwoFactorEnabled = false,
                            UserName = "CenterReviewer"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Center");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterOwnerUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<int>("FKGenderId")
                        .HasColumnType("int");

                    b.Property<string>("FKUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FourthName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FKCenterId");

                    b.HasIndex("FKGenderId");

                    b.HasIndex("FKUserId")
                        .IsUnique();

                    b.ToTable("CenterOwnerUser");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FKTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FKTypeId");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("FAQType");
                });

            modelBuilder.Entity("Qurrah.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.GenderDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKGenderId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKGenderId");

                    b.HasIndex("FKLanguageId", "FKGenderId")
                        .IsUnique();

                    b.ToTable("GenderDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ذكر",
                            FKGenderId = 1,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Male",
                            FKGenderId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "أنثى",
                            FKGenderId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Female",
                            FKGenderId = 2,
                            FKLanguageId = 2
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCulture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<bool>("RTL")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCulture")
                        .IsUnique();

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            LanguageCulture = "ar-SA",
                            Name = "Arabic",
                            Published = true,
                            RTL = true
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            LanguageCulture = "en-US",
                            Name = "English",
                            Published = true,
                            RTL = false
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.LanguageDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKInLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKInLanguageId");

                    b.HasIndex("FKLanguageId", "FKInLanguageId")
                        .IsUnique();

                    b.ToTable("LanguageDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "العربية",
                            FKInLanguageId = 1,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Arabic",
                            FKInLanguageId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "الإنجليزية",
                            FKInLanguageId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "English",
                            FKInLanguageId = 2,
                            FKLanguageId = 2
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.LocalizedProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LocaleKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocaleKeyGroup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocaleValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FKLanguageId");

                    b.HasIndex("LocaleKeyGroup");

                    b.HasIndex("LocaleKeyGroup", "LocaleKey", "LocaleValue", "FKLanguageId", "EntityId")
                        .IsUnique();

                    b.ToTable("LocalizedProperty");
                });

            modelBuilder.Entity("Qurrah.Entities.ParentUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FKGenderId")
                        .HasColumnType("int");

                    b.Property<string>("FKUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FourthName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FKGenderId");

                    b.HasIndex("FKUserId")
                        .IsUnique();

                    b.ToTable("ParentUser");
                });

            modelBuilder.Entity("Qurrah.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CenterApprover"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Parent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Center"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qurrah.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("FKCreatedByUserId");

                    b.HasOne("Qurrah.Entities.UserType", "UserType")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("FKUserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterOwnerUser", b =>
                {
                    b.HasOne("Qurrah.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Gender", "Gender")
                        .WithMany("CenterOwnerUsers")
                        .HasForeignKey("FKGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("FKUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Center");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQ", b =>
                {
                    b.HasOne("Qurrah.Entities.FAQType", "FAQType")
                        .WithMany("FAQs")
                        .HasForeignKey("FKTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FAQType");
                });

            modelBuilder.Entity("Qurrah.Entities.GenderDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Gender", "Gender")
                        .WithMany("GenderDescriptions")
                        .HasForeignKey("FKGenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("GenderDescriptions")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.LanguageDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "InLanguage")
                        .WithMany()
                        .HasForeignKey("FKInLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("LanguageDescriptions")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.LocalizedProperty", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("LocalizedProperties")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.ParentUser", b =>
                {
                    b.HasOne("Qurrah.Entities.Gender", "Gender")
                        .WithMany("ParentUsers")
                        .HasForeignKey("FKGenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("FKUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQType", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("Qurrah.Entities.Gender", b =>
                {
                    b.Navigation("CenterOwnerUsers");

                    b.Navigation("GenderDescriptions");

                    b.Navigation("ParentUsers");
                });

            modelBuilder.Entity("Qurrah.Entities.Language", b =>
                {
                    b.Navigation("GenderDescriptions");

                    b.Navigation("LanguageDescriptions");

                    b.Navigation("LocalizedProperties");
                });

            modelBuilder.Entity("Qurrah.Entities.UserType", b =>
                {
                    b.Navigation("ApplicationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
