// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qurrah.Data;

#nullable disable

namespace Qurrah.Data.Migrations
{
    [DbContext(typeof(QurrahDbContext))]
    [Migration("20230725123513_ModifyCenterLicense")]
    partial class ModifyCenterLicense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c4f8fb8a-af31-4682-8c14-69b31debe396",
                            Name = "Parent",
                            NormalizedName = "Parent"
                        },
                        new
                        {
                            Id = "9339b590-e6c7-45bd-90aa-707f36b8b3ad",
                            Name = "Center",
                            NormalizedName = "Center"
                        },
                        new
                        {
                            Id = "6e9c36c2-7efa-44e6-8403-0cce3a8f8bbe",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "72b941f0-2b63-4bed-844f-448bdee0d8a6",
                            Name = "CenterApprover",
                            NormalizedName = "CenterApprover"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ffe35a84-5f8c-4b16-922f-64fa661cb3ab",
                            RoleId = "6e9c36c2-7efa-44e6-8403-0cce3a8f8bbe"
                        },
                        new
                        {
                            UserId = "41c2e096-8eed-4a16-908b-bdeada951859",
                            RoleId = "72b941f0-2b63-4bed-844f-448bdee0d8a6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Qurrah.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FKCreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FKGenderId")
                        .HasColumnType("int");

                    b.Property<int>("FKUserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FourthName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FKCreatedByUserId");

                    b.HasIndex("FKGenderId");

                    b.HasIndex("FKUserTypeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ffe35a84-5f8c-4b16-922f-64fa661cb3ab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35d7e2f6-f988-4d60-8fda-b2f7deb87977",
                            CreatedOn = new DateTime(2023, 7, 25, 15, 35, 12, 603, DateTimeKind.Local).AddTicks(3852),
                            Email = "Admin@Qurrah.com",
                            EmailConfirmed = false,
                            FKGenderId = 1,
                            FKUserTypeId = 1,
                            FirstName = "Administrator",
                            FourthName = "",
                            IdNumber = "",
                            LockoutEnabled = false,
                            MobileNumber = "",
                            NormalizedEmail = "Admin@Qurrah.com",
                            NormalizedUserName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEBvHbPB5ySPnOfWDisVKMMapC5SrBDMQLH+YcyIEJ6r027pIe9N11iPodc1d3wM6Cw==",
                            PhoneNumber = "0543700744",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cd39a8a1-27b2-4bb3-b6ae-a35db73fe45d",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "41c2e096-8eed-4a16-908b-bdeada951859",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a618e807-17c4-460b-9274-db49f3283251",
                            CreatedOn = new DateTime(2023, 7, 25, 15, 35, 12, 703, DateTimeKind.Local).AddTicks(3495),
                            Email = "CenterReviewer@Qurrah.com",
                            EmailConfirmed = false,
                            FKGenderId = 1,
                            FKUserTypeId = 2,
                            FirstName = "Reviewer",
                            FourthName = "",
                            IdNumber = "",
                            LockoutEnabled = false,
                            MobileNumber = "",
                            NormalizedEmail = "CenterReviewer@Qurrah.com",
                            NormalizedUserName = "CenterReviewer",
                            PasswordHash = "AQAAAAIAAYagAAAAEHifRI25gxKYx0XVrhi7E+kht0hPOakH0LEbJ9gja/4vOXqymjWSGPrBSZM3N5C0Hg==",
                            PhoneNumber = "0543700745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be1d5427-a7d7-41d1-af4f-2e308c2d8c0e",
                            TwoFactorEnabled = false,
                            UserName = "CenterReviewer"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKCenterStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("FKCenterTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FKCreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("FKIBANFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FKStatusUpdatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FKCenterStatusId");

                    b.HasIndex("FKCenterTypeId");

                    b.HasIndex("FKCreatedByUserId");

                    b.HasIndex("FKIBANFileId")
                        .IsUnique()
                        .HasFilter("[FKIBANFileId] IS NOT NULL");

                    b.HasIndex("FKStatusUpdatedByUserId");

                    b.HasIndex("IBAN")
                        .IsUnique()
                        .HasFilter("[IBAN] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Center");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<Guid>("FKFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FKStatusUpdatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FKFileId")
                        .IsUnique();

                    b.HasIndex("FKStatusId");

                    b.HasIndex("FKStatusUpdatedByUserId");

                    b.HasIndex("FKCenterId", "LicenseNumber")
                        .IsUnique();

                    b.ToTable("CenterLicense");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicenseStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CenterLicenseStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UnderConsideration"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicenseStatusDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("FKStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKStatusId");

                    b.HasIndex("FKLanguageId", "FKStatusId")
                        .IsUnique();

                    b.ToTable("CenterLicenseStatusDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Under Consideration",
                            FKLanguageId = 2,
                            FKStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "قيد الدراسة",
                            FKLanguageId = 1,
                            FKStatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Approved",
                            FKLanguageId = 2,
                            FKStatusId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "مقبول",
                            FKLanguageId = 1,
                            FKStatusId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rejected",
                            FKLanguageId = 2,
                            FKStatusId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "مرفوض",
                            FKLanguageId = 1,
                            FKStatusId = 3
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CenterStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UnderConsideration"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterStatusDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CenterStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKCenterStatusId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CenterStatusId");

                    b.HasIndex("FKLanguageId", "FKCenterStatusId")
                        .IsUnique();

                    b.ToTable("CenterStatusDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Under Consideration",
                            FKCenterStatusId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "قيد الدراسة",
                            FKCenterStatusId = 1,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Approved",
                            FKCenterStatusId = 2,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "مقبول",
                            FKCenterStatusId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rejected",
                            FKCenterStatusId = 3,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "مرفوض",
                            FKCenterStatusId = 3,
                            FKLanguageId = 1
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CenterType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dependent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InDependent"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterTypeDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKCenterTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKCenterTypeId");

                    b.HasIndex("FKLanguageId", "FKCenterTypeId")
                        .IsUnique();

                    b.ToTable("CenterTypeDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "InDependent",
                            FKCenterTypeId = 2,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "غير مستقل",
                            FKCenterTypeId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dependent",
                            FKCenterTypeId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "مستقل",
                            FKCenterTypeId = 1,
                            FKLanguageId = 1
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.CenterUser", b =>
                {
                    b.Property<int>("FKCenterId")
                        .HasColumnType("int");

                    b.Property<string>("FKUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FKCenterId", "FKUserId");

                    b.HasIndex("FKUserId");

                    b.ToTable("CenterUser");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FKTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FKTypeId");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("FAQType");
                });

            modelBuilder.Entity("Qurrah.Entities.FileDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKFileTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKFileTypeId");

                    b.ToTable("FileDetails");
                });

            modelBuilder.Entity("Qurrah.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "application/pdf",
                            Name = "PDF"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            Name = "DOCX"
                        },
                        new
                        {
                            Id = 3,
                            ContentType = "application/msword",
                            Name = "DOC"
                        },
                        new
                        {
                            Id = 4,
                            ContentType = "image/x-png",
                            Name = "PNG"
                        },
                        new
                        {
                            Id = 5,
                            ContentType = "image/jpeg",
                            Name = "JPG"
                        },
                        new
                        {
                            Id = 6,
                            ContentType = "image/jpeg",
                            Name = "JPEG"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.GenderDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKGenderId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKGenderId");

                    b.HasIndex("FKLanguageId", "FKGenderId")
                        .IsUnique();

                    b.ToTable("GenderDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ذكر",
                            FKGenderId = 1,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Male",
                            FKGenderId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "أنثى",
                            FKGenderId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Female",
                            FKGenderId = 2,
                            FKLanguageId = 2
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCulture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<bool>("RTL")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCulture")
                        .IsUnique();

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            LanguageCulture = "ar-SA",
                            Name = "Arabic",
                            Published = true,
                            RTL = true
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            LanguageCulture = "en-US",
                            Name = "English",
                            Published = true,
                            RTL = false
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.LanguageDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKInLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKInLanguageId");

                    b.HasIndex("FKLanguageId", "FKInLanguageId")
                        .IsUnique();

                    b.ToTable("LanguageDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "العربية",
                            FKInLanguageId = 1,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Arabic",
                            FKInLanguageId = 2,
                            FKLanguageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "الإنجليزية",
                            FKInLanguageId = 1,
                            FKLanguageId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "English",
                            FKInLanguageId = 2,
                            FKLanguageId = 2
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.LocalizedProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMultiLine")
                        .HasColumnType("bit");

                    b.Property<string>("LocaleKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocaleKeyGroup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocaleValue")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKLanguageId");

                    b.HasIndex("LocaleKeyGroup");

                    b.HasIndex("LocaleKeyGroup", "LocaleKey", "FKLanguageId", "EntityId")
                        .IsUnique();

                    b.ToTable("LocalizedProperty");
                });

            modelBuilder.Entity("Qurrah.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CenterApprover"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Parent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Center"
                        });
                });

            modelBuilder.Entity("Qurrah.Entities.UserTypeDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("FKUserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKUserTypeId");

                    b.HasIndex("FKLanguageId", "FKUserTypeId")
                        .IsUnique();

                    b.ToTable("UserTypeDescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "مدير النظام",
                            FKLanguageId = 1,
                            FKUserTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Administrator",
                            FKLanguageId = 2,
                            FKUserTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "ولي أمر",
                            FKLanguageId = 1,
                            FKUserTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Parent",
                            FKLanguageId = 2,
                            FKUserTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "مركز",
                            FKLanguageId = 1,
                            FKUserTypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Center",
                            FKLanguageId = 2,
                            FKUserTypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            Description = "مراجع مراكز",
                            FKLanguageId = 1,
                            FKUserTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Center Approver",
                            FKLanguageId = 2,
                            FKUserTypeId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qurrah.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Qurrah.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("FKCreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qurrah.Entities.Gender", "Gender")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("FKGenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.UserType", "UserType")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("FKUserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Gender");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Qurrah.Entities.Center", b =>
                {
                    b.HasOne("Qurrah.Entities.CenterStatus", "CenterStatus")
                        .WithMany()
                        .HasForeignKey("FKCenterStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.CenterType", "CenterType")
                        .WithMany()
                        .HasForeignKey("FKCenterTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qurrah.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CentersCreatedBy")
                        .HasForeignKey("FKCreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.FileDetails", "File")
                        .WithMany("Centers")
                        .HasForeignKey("FKIBANFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qurrah.Entities.ApplicationUser", "StatusUpdatedByUser")
                        .WithMany("CentersUpdatedBy")
                        .HasForeignKey("FKStatusUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CenterStatus");

                    b.Navigation("CenterType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("File");

                    b.Navigation("StatusUpdatedByUser");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicense", b =>
                {
                    b.HasOne("Qurrah.Entities.Center", "Center")
                        .WithMany("CenterLicenses")
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.FileDetails", "FileDetails")
                        .WithMany("CenterLicenses")
                        .HasForeignKey("FKFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.CenterLicenseStatus", "Status")
                        .WithMany()
                        .HasForeignKey("FKStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", "StatusUpdatedByUser")
                        .WithMany("CenterLicenses")
                        .HasForeignKey("FKStatusUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Center");

                    b.Navigation("FileDetails");

                    b.Navigation("Status");

                    b.Navigation("StatusUpdatedByUser");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicenseStatusDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("CenterLicenseStatusDescriptions")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.CenterLicenseStatus", "CenterLicenseStatus")
                        .WithMany("CenterLicenseStatusDescriptions")
                        .HasForeignKey("FKStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CenterLicenseStatus");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterStatusDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.CenterStatus", "CenterStatus")
                        .WithMany("CenterStatusDescriptions")
                        .HasForeignKey("CenterStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CenterStatus");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterTypeDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.CenterType", "CenterType")
                        .WithMany("CenterTypeDescriptions")
                        .HasForeignKey("FKCenterTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CenterType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterUser", b =>
                {
                    b.HasOne("Qurrah.Entities.Center", "Center")
                        .WithMany("CenterUsers")
                        .HasForeignKey("FKCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.ApplicationUser", "User")
                        .WithMany("CenterUsers")
                        .HasForeignKey("FKUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQ", b =>
                {
                    b.HasOne("Qurrah.Entities.FAQType", "FAQType")
                        .WithMany("FAQs")
                        .HasForeignKey("FKTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FAQType");
                });

            modelBuilder.Entity("Qurrah.Entities.FileDetails", b =>
                {
                    b.HasOne("Qurrah.Entities.FileType", "FileType")
                        .WithMany("FileDetails")
                        .HasForeignKey("FKFileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("Qurrah.Entities.GenderDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Gender", "Gender")
                        .WithMany("GenderDescriptions")
                        .HasForeignKey("FKGenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("GenderDescriptions")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.LanguageDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "InLanguage")
                        .WithMany("InLanguageDescriptions")
                        .HasForeignKey("FKInLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("LanguageDescriptions")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.LocalizedProperty", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany("LocalizedProperties")
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Qurrah.Entities.UserTypeDescription", b =>
                {
                    b.HasOne("Qurrah.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("FKLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qurrah.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("FKUserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Qurrah.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CenterLicenses");

                    b.Navigation("CenterUsers");

                    b.Navigation("CentersCreatedBy");

                    b.Navigation("CentersUpdatedBy");
                });

            modelBuilder.Entity("Qurrah.Entities.Center", b =>
                {
                    b.Navigation("CenterLicenses");

                    b.Navigation("CenterUsers");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterLicenseStatus", b =>
                {
                    b.Navigation("CenterLicenseStatusDescriptions");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterStatus", b =>
                {
                    b.Navigation("CenterStatusDescriptions");
                });

            modelBuilder.Entity("Qurrah.Entities.CenterType", b =>
                {
                    b.Navigation("CenterTypeDescriptions");
                });

            modelBuilder.Entity("Qurrah.Entities.FAQType", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("Qurrah.Entities.FileDetails", b =>
                {
                    b.Navigation("CenterLicenses");

                    b.Navigation("Centers");
                });

            modelBuilder.Entity("Qurrah.Entities.FileType", b =>
                {
                    b.Navigation("FileDetails");
                });

            modelBuilder.Entity("Qurrah.Entities.Gender", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("GenderDescriptions");
                });

            modelBuilder.Entity("Qurrah.Entities.Language", b =>
                {
                    b.Navigation("CenterLicenseStatusDescriptions");

                    b.Navigation("GenderDescriptions");

                    b.Navigation("InLanguageDescriptions");

                    b.Navigation("LanguageDescriptions");

                    b.Navigation("LocalizedProperties");
                });

            modelBuilder.Entity("Qurrah.Entities.UserType", b =>
                {
                    b.Navigation("ApplicationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
